server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route  #路由的ID,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001        #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址(eureka上注册的应用名)
          predicates:
            - Path=/payment/get/**          #断言,路径匹配的进行路由

        - id: payment_routh2 #payment_route  #路由的ID,没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址(eureka上注册的应用名)
          predicates:
            - Path=/payment/lb/**            #断言,路径匹配的进行路由
            #- After=2020-04-09T22:28:36.374+08:00[Asia/Shanghai] #在配置时间后才能访问
            #- Before=2020-04-09T23:28:36.374+08:00[Asia/Shanghai] #在配置时间前才能访问
            #- Between=2020-04-09T22:28:36.374+08:00[Asia/Shanghai],2020-04-09T23:28:36.374+08:00[Asia/Shanghai] #在配置时间范围内才能访问
            #- Cookie=username,62799   #请求的cookie要带username属性 而且要符合62799(也可以配正则)
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id 而且要符合正则要为整数

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka

